global:
  imagePullPolicy: IfNotPresent
  services:
    aws:
      region: us-east-1
      az: us-east-1a
      efs:
        id: fs-47cd610e

storage:
  name: tensorflow-fs
  accessMode: ReadWriteMany
  pv: 
    capacity: "900Gi"
  pvc:
    name: tensorflow-fs
    request: "750Gi"

tfCluster:
  deploy: true
  service:
    name: tensorflow-cluster
    internalPort: 8080
    externalPort: 8080
    type: ClusterIP
  image: 
    repo: vktk
    name: flowers-inception:latest
    dockerTagCpu: train-0.11-0.0.8
    dockerTagGpu: train-0.11-gpu-0.0.8
    # dockerTagGpu: train-0.11-0.0.8
    # dockerTagCpu: train-0.9-1
    # dockerTagGpu: train-0.9-gpu-1
  settings:
    dataset: imagenet
    isGpu: true
    nbGpuPerNode: 1
    jobs: 
      ps: 1
      worker: 2
  resources:
    requests:
      cpu: 1000m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi
